### ISSUE TITLE
Make a good Readme 📖✌️

### ISSUE THREAD

**Issue by Pritam0077** [Pritam0077/Moviefinder#4]
Try to make good readme documentation...

**Comment by mikolaszko** [comment]
Okay, I've written some good read mes. Could you perhaps tell me more about the project?

**Comment by mikolaszko** [comment]
I went ahead and created a pull request for that issue, I will wait for some feedback

**Comment by Pritam0077** [comment]
It is basically a simple React project it fetches the movie data from an API and displays the movie's
Tech stack used is Reactjs

**Comment by Pritam0077** [comment]
ok 👍
